"""add_lead_status_and_tasks

Adds:
  1. leadstatus ENUM type
  2. lead_status column on contacts table
  3. taskstatus / taskpriority ENUM types
  4. tasks table (full schema matching app/models/task.py)

Revision ID: 002_add_lead_status_and_tasks
Revises: 001_initial_schema
Create Date: 2025-01-01 00:00:00.000000
"""

from typing import Sequence, Union

from alembic import op

revision: str = "002_add_lead_status_and_tasks"
down_revision: Union[str, None] = "001_initial_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── 1. ENUM types (idempotent) ────────────────────────────────────────────
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE leadstatus AS ENUM ('new','contacted','qualified','converted','lost');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;

        DO $$ BEGIN
            CREATE TYPE taskstatus AS ENUM ('todo','in_progress','done','cancelled');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;

        DO $$ BEGIN
            CREATE TYPE taskpriority AS ENUM ('low','medium','high','urgent');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)

    # ── 2. lead_status column on contacts ─────────────────────────────────────
    op.execute("""
        ALTER TABLE contacts
            ADD COLUMN IF NOT EXISTS lead_status leadstatus NOT NULL DEFAULT 'new';

        CREATE INDEX IF NOT EXISTS idx_contacts_workspace_lead_status
            ON contacts (workspace_id, lead_status);
    """)

    # ── 3. tasks table ────────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE IF NOT EXISTS tasks (
            -- Primary key (UUID generated by Python)
            id              VARCHAR(36)  PRIMARY KEY,

            -- Multi-tenancy
            workspace_id    VARCHAR(36)  NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,

            -- Content
            title           VARCHAR(500) NOT NULL,
            description     TEXT,

            -- Status & priority
            status          taskstatus   NOT NULL DEFAULT 'todo',
            priority        taskpriority NOT NULL DEFAULT 'medium',

            -- Scheduling
            due_at          TIMESTAMPTZ,
            completed_at    TIMESTAMPTZ,

            -- Relations (all optional)
            contact_id      VARCHAR(36)  REFERENCES contacts(id) ON DELETE SET NULL,
            deal_id         VARCHAR(36)  REFERENCES deals(id)    ON DELETE SET NULL,
            assigned_to     VARCHAR(36)  REFERENCES users(id)    ON DELETE SET NULL,
            created_by      VARCHAR(36)  REFERENCES users(id)    ON DELETE SET NULL,

            -- Soft-delete
            deleted_at      TIMESTAMPTZ,

            -- Timestamps
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );

        -- Performance indexes
        CREATE INDEX IF NOT EXISTS idx_task_workspace_id
            ON tasks (workspace_id);

        CREATE INDEX IF NOT EXISTS idx_task_workspace_status
            ON tasks (workspace_id, status);

        CREATE INDEX IF NOT EXISTS idx_task_workspace_due
            ON tasks (workspace_id, due_at)
            WHERE due_at IS NOT NULL;

        CREATE INDEX IF NOT EXISTS idx_task_workspace_assignee
            ON tasks (workspace_id, assigned_to)
            WHERE assigned_to IS NOT NULL;

        CREATE INDEX IF NOT EXISTS idx_task_contact_id
            ON tasks (contact_id)
            WHERE contact_id IS NOT NULL;

        CREATE INDEX IF NOT EXISTS idx_task_deal_id
            ON tasks (deal_id)
            WHERE deal_id IS NOT NULL;

        CREATE INDEX IF NOT EXISTS idx_task_deleted_at
            ON tasks (deleted_at)
            WHERE deleted_at IS NULL;
    """)


def downgrade() -> None:
    op.execute("""
        DROP TABLE IF EXISTS tasks;

        ALTER TABLE contacts
            DROP COLUMN IF EXISTS lead_status;

        DROP TYPE IF EXISTS leadstatus;
        DROP TYPE IF EXISTS taskstatus;
        DROP TYPE IF EXISTS taskpriority;
    """)
